### ISSUE TITLE
[tuna]Mirror Request for new mirror chocolatey

### ISSUE THREAD

**Issue by Alex6357** [tuna/issues#1021] opened 2020-10-31 13:24 UTC
#### 项目名称与简介(Project Intro.)
Chocolatey Software is focused on helping our community, customers, and partners with solutions that help fill the gaps that are often ignored. We offer a simple, pragmatic, and open approach to software management.
#### 上游地址与镜像方法(How to Mirror)
https://chocolatey.org/packages
https://www.chocolatey.org/docs/how-to-host-feed
https://www.chocolatey.org/docs/chocolatey-configuration
#### 其他信息(Other)
- 镜像大小(Mirror Size): 
2-5TB

**Comment by ZenithalHourlyRate** [comment] 2020-10-31 14:13
Duplicate of #54

**Closed** 2020-10-31 15:28 UTC
