### ISSUE TITLE
[tuna]404 at /jenkins/war/2.235.3/jenkins.war

### ISSUE THREAD

**Issue by zz99132242** [tuna/issues#920] opened 2020-08-05 03:02 UTC
https://mirrors.tuna.tsinghua.edu.cn/jenkins/war/2.235.3/jenkins.war 404

**Comment by phy25** [comment] 2020-08-05 03:12
Duplicate of #862 .

**Comment by shankerwangmiao** [comment] 2020-08-05 03:33
thx @phy25

**Closed by shankerwangmiao** 2020-08-05 03:33 UTC
Labels: Service Issue
